name = "khybershawls-app"
main = ".next/standalone/server.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "khybershawls"
database_id = "db0f3978-76b8-4816-b1ea-2ba3f487d932"
